"""Pure object and diagnostic projections over explicitly routed documents."""
from . import _producer_parser as producer
from .documents import _validate_context
from .identity import copy_files


def build_document_projections(sources, *, registered_prefixes):
    """Return exact object/diagnostic wire bytes for ordered (path, family, bytes).

    The caller selects and orders the corpus and supplies family policy. No
    locations, provenance, snapshot validation or publication is performed here.
    Duplicate paths are rejected rather than silently replacing source context.
    """
    prepared, prefixes = _prepare_sources(sources, registered_prefixes)
    scanned = producer.scan(prepared, prefixes)
    return _document_files(scanned, frozenset(p for p, _, _ in prepared))


def _prepare_sources(sources, registered_prefixes):
    prefixes = _validate_context(b"", "context.md", "context", registered_prefixes)
    prepared = []
    seen = set()
    for path, family, data in sources:
        _validate_context(data, path, family, prefixes)
        if path in seen:
            raise ValueError("Duplicate document path")
        seen.add(path)
        prepared.append((path, family, data.decode("utf-8", errors="replace")))
    return prepared, prefixes


def _document_files(scanned, admitted_documents):
    objects, diagnostics, _expectations = producer.build_projection_bundle_with_expectations(
        scanned, admitted_documents=admitted_documents)
    return {
        kind + "/" + name + ".json": render(payload).encode("utf-8")
        for kind, payloads, render in (
            ("index", objects, producer._render),
            ("diagnostics", diagnostics, producer._diagnostic_render),
        )
        for name, payload in payloads.items()
    }


def build_projection_files(sources, *, registered_prefixes, archives, archive_families):
    """Build all three projection members and return (files, location diagnostics).

    Archives maps explicit relative paths to ZIP bytes; archive_families maps
    (archive path, Markdown member path) to a family. Pinned archive limits apply.
    The host must select the complete corpus. These generated bytes still require
    provenance and bundle validation before publication.
    """
    prepared, prefixes = _prepare_sources(sources, registered_prefixes)
    archive_bytes = dict(archives)
    if archive_bytes:
        archive_bytes = copy_files(archive_bytes)
    families = dict(archive_families)
    for key, family in families.items():
        if not isinstance(key, tuple) or len(key) != 2:
            raise ValueError("Archive family key must identify archive and member")
        archive, member = key
        _validate_context(b"", member, family, prefixes)
        if archive not in archive_bytes:
            raise ValueError("Archive family references an unsupplied archive")
    def family_for_member(archive, member):
        try:
            return families[(archive, member)]
        except KeyError as exc:
            raise ValueError("Explicit archive member family required") from exc
    scanned = producer.scan(prepared, prefixes)
    files = _document_files(scanned, frozenset(p for p, _, _ in prepared))
    locations, diagnostics = producer.locations.build_location_index(
        {p:text for p, _, text in prepared}, scanned['docs'], archive_bytes, family_for_member)
    files.update({'locations/' + name + '.json': producer.locations.render(payload).encode('utf-8')
                  for name, payload in locations.items()})
    return files, diagnostics
