"""Full pinned producer regeneration over declared source fixture bytes.

Developer reference harness only, not the portable producer implementation.
Inputs are materialized only in a temporary directory. No repository is changed.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys
import tempfile

sys.path.insert(0,str(Path(__file__).resolve().parent))
from reproduce_wire_vectors import load_pinned_scanner
from check_git_provider import load_verified_wheels, reject_process_and_network


def regenerate(source):
    package = Path(__file__).resolve().parents[1]
    sys.path[:0] = [str(package/"src"),str(package/"tests_git")]
    from dulwich.repo import Repo
    from sbc_tools.git_reader import GitCommitReader
    from test_provenance_inputs import commit_files
    scanner = load_pinned_scanner(source)
    fixtures = Path(__file__).resolve().parents[1]/"tests/fixtures"
    inputs = json.loads((fixtures/"producer-source-vectors.json").read_bytes())
    expected = json.loads((fixtures/"projection-wire-vectors.json").read_bytes())
    results = []
    for case in inputs["cases"]:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)/"materialized"
            root.mkdir()
            git_path = Path(temp)/"fixture.git"
            git_path.mkdir()
            committed_files = {}
            for path, text in case["inputs"].items():
                if (not path or "\\" in path or ":" in path
                        or any(p in {"", ".", ".."} for p in path.split("/"))):
                    raise ValueError("Unsafe fixture path")
                committed_files[path] = text.encode("utf-8")
            with Repo.init_bare(str(git_path)) as repo:
                commit = commit_files(repo,committed_files)
            with GitCommitReader(str(git_path)) as reader:
                for entry in reader.entries(commit):
                    target = root/entry.path
                    target.parent.mkdir(parents=True,exist_ok=True)
                    target.write_bytes(reader.read_blob(commit,entry.path))
            data = scanner.scan(root)
            objects, diagnostics, expectations = scanner.build_projection_bundle_with_expectations(data)
            locations, location_diagnostics = scanner.locations.build_location_index(root,data["docs"],scanner.family_of)
            expectations = scanner.bind_location_expectations(expectations,locations)
            scanner._validate_projection_bundle(objects,locations,diagnostics,
                registered_prefixes=set(data["registered_prefixes"]),expectations=expectations)
            actual = {}
            for kind, payloads in (("index",objects),("locations",locations),("diagnostics",diagnostics)):
                render = scanner._diagnostic_render if kind == "diagnostics" else scanner._render
                for name,payload in payloads.items():
                    actual[kind+"/"+name+".json"] = render(payload)
            wanted = next(c["files"] for c in expected["cases"] if c["name"] == case["name"])
            if actual != wanted:
                differences = sorted(p for p in set(actual)|set(wanted) if actual.get(p) != wanted.get(p))
                raise ValueError(case["name"] + ": regenerated bytes differ: " + repr(differences))
            results.append({"case":case["name"],"source_commit":commit,"files":len(actual),"status":"exact match",
                "location_diagnostics":len(location_diagnostics),
                "sha256":{p:hashlib.sha256(text.encode()).hexdigest() for p,text in sorted(actual.items())}})
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("source",type=Path)
    parser.add_argument("wheel_directory",type=Path)
    args = parser.parse_args()
    load_verified_wheels(args.wheel_directory)
    sys.addaudithook(reject_process_and_network)
    print(json.dumps({"scope":"Full pinned reference producer on committed fixture bytes; temporary files only",
                      "cases":regenerate(args.source)},indent=2))
